# Generated by Django 3.2 on 2021-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210904_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=2007, upload_to='articles/'),
            preserve_default=False,
        ),
    ]
